name: Laravel

on:
  push:
    branches: [master]
  pull_request:
    branches: [develop,master]
    types: [opened, synchronize]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Redundant Builds
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{github.token}}
