name: Laravel

on:
  push:
    branches: [master]
  pull_request:
    branches: [develop,master]
    types: [opened, synchronize]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Redundant Builds
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{github.token}}
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1.2'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: lint
      run: ./vendor/bin/pint